### ISSUE TITLE
Latest version removes Go tracebacks from dev server

### ISSUE THREAD

**Issue by exgeo-jcarter** [GoogleCloudPlatform/gcloud#27]
After most recent gcloud components update, there are no longer any tracebacks shown when my application won't compile. This makes it very hard to find my errors. I have reverted to previous gcloud version to get the tracebacks back. Why would you remove this?? Please add tracebacks back into the dev server.

**Comment by stephenmw** [comment]
Known issue. Will be fixed next release (Wed/Thurs).
